### ISSUE TITLE
MoreLikeThis Vertical Expansion for Movies bug

### ISSUE THREAD

**Issue by alagappanr** [alagappanr/orangehummer#17]
3283138 [qtp1773103387-10] INFO  org.apache.solr.core.SolrCore  – [QACollection] webapp=/solr path=/select params={mlt.mindf=1&mlt.fl=director&mlt.count=5&fl=name,id&indent=true&q=mad+dog+and+glory&mlt.mintf=1&mlt=true&wt=json&fq=type:film} hits=46 status=500 QTime=3 
3283140 [qtp1773103387-10] ERROR org.apache.solr.servlet.SolrDispatchFilter  – null:org.apache.solr.search.EarlyTerminatingCollectorException
    at org.apache.solr.search.EarlyTerminatingCollector.collect(EarlyTerminatingCollector.java:72)
    at org.apache.lucene.search.BooleanScorer2.score(BooleanScorer2.java:289)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:627)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:297)
    at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1501)
    at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1367)
    at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:474)
    at org.apache.solr.search.SolrIndexSearcher.getDocList(SolrIndexSearcher.java:1230)
    at org.apache.solr.handler.MoreLikeThisHandler$MoreLikeThisHelper.getMoreLikeThis(MoreLikeThisHandler.java:365)
    at org.apache.solr.handler.component.MoreLikeThisComponent.getMoreLikeThese(MoreLikeThisComponent.java:356)
    at org.apache.solr.handler.component.MoreLikeThisComponent.process(MoreLikeThisComponent.java:113)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:208)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1859)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:703)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:406)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:368)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:724)

**Comment by techpalaniappanm** [comment]
Changed the count to 8. Resolved the issue.
Try restricting the count as needed in front end.
